In [12]:
li = [1,2,3]
si = [4,5,6,'a']


In [10]:
li.append(si[0])

In [13]:
li*2

[1, 2, 3, 1, 2, 3]

In [14]:
li

[1, 2, 3]

In [15]:
si*2

[4, 5, 6, 'a', 4, 5, 6, 'a']

In [27]:
[x+1 for x in arr]

[2, 3, 4]

In [20]:
import numpy as np
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [26]:
print(arr+2)

[3 4 5]


In [24]:
print(li)*2

[1, 2, 3]


TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'

In [25]:
arr*2

array([2, 4, 6])

In [28]:
import pandas as pd


In [29]:
ss = pd.Series([1,2,3],index=['a','b','c'])
ss

a    1
b    2
c    3
dtype: int64

In [30]:
print(ss)


a    1
b    2
c    3
dtype: int64


In [54]:
a = np.array([[[1, 2], [3, 4],[[6,7]]])
print(a)
a.shape

SyntaxError: closing parenthesis ')' does not match opening parenthesis '[' (186184104.py, line 1)

In [47]:
a = np.array([[1, 2], [3, 4]])
print(a)

b = np.array([[5, 6], [7, 8]])
print('\n',b)
result = np.dstack((a, b))   # Shape: (2, 2, 2)

[[1 2]
 [3 4]]

 [[5 6]
 [7 8]]


In [46]:
print(result)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [33]:
a

array([[1, 2],
       [3, 4]])

In [38]:
result.shape

(2, 2, 2)

In [37]:
type(a)

numpy.ndarray

In [42]:
arr = np.array([[1, 2], [3, 4]])
print(arr)
flat_arr = arr.flatten()     # [1, 2, 3, 4]
print(flat_arr)

[[1 2]
 [3 4]]
[1 2 3 4]


In [55]:
arr = np.array([1, 2, 3])
print(arr)
arr2d = np.array([[1], [2], [3]])
print(arr2d)
result = arr + arr2d
print("\n",result)
result.shape

[1 2 3]
[[1]
 [2]
 [3]]

 [[2 3 4]
 [3 4 5]
 [4 5 6]]


(3, 3)